### ISSUE TITLE
Python3 version of (wiki) base.html

### ISSUE THREAD

**Issue by WeaverStever** [webpy/webpy-examples#4]
Pretty simple to get wiki sample working in Python3

Python2 "has_key" is deprecated.

**Python2.x**
~~~
<head>
   <!--./wiki/templates/base.html (Python2) -->
    
    $if page.has_key('title'):
        <title>$page.title</title>
    .........
</head>
~~~

**Python3.x**
~~~
<head>
   <!--./wiki/templates/base.html (Python3) -->
    $if 'title' in page:
        <title>$page.title</title>
    ........
</head>
~~~

Everything else in the wiki sample appears to be working with Python 3.5.2 using import [pymysql ](https://www.tutorialspoint.com/python3/python_database_access.htm)(in ,/wiki/model.py)  

Thought I should share, 
-- Thank You!

**Comment by iredmail** [comment]
Hi @WeaverStever,

Would you mind sending a pull request to fix it? :)

**Comment by WeaverStever** [comment]
@iredmail 

Sorry, I looked over how to do a pull request, unclear to me.

I tested the change in Python 2.7.12, with MySQLdb connector, the updated template (base.html) works.  

Can you do the commit w/o my pull request?

**Comment by iredmail** [comment]
Already committed: https://github.com/webpy/webpy-examples/commit/003208e1afcfa72cba0334c15e539628a8ee2b3c

Thanks. :)
